# Generated by Django 4.2.4 on 2023-08-20 07:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_customer_udpated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="udpated_at",
        ),
    ]
