# Generated by Django 4.2.4 on 2023-08-20 13:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_remove_customer_udpated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
